package com.my51c.see51.app;


import android.content.Context;
import android.content.Intent;
import android.content.res.Configuration;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.widget.ImageView;
import android.widget.ImageView.ScaleType;

import com.android.volley.DefaultRetryPolicy;
import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.my51c.see51.BaseActivity;
import com.my51c.see51.app.bean.AccountModel;
import com.my51c.see51.app.bean.BucDataModel;
import com.my51c.see51.app.bean.LnbDataModel;
import com.my51c.see51.app.bean.ModemBean;
import com.my51c.see51.app.bean.StarCodeModel;
import com.my51c.see51.app.http.XTHttpUtil;
import com.my51c.see51.app.service.GpsService;
import com.my51c.see51.common.AppData;
import com.my51c.see51.widget.SharedPreferenceManager;
import com.synertone.netAssistant.R;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.InputStream;

public class SplashActivity extends BaseActivity {
    public static Bitmap readBitMap(Context context, int resId) {
        BitmapFactory.Options opt = new BitmapFactory.Options();
        opt.inPreferredConfig = Bitmap.Config.ARGB_8888;
        opt.inPurgeable = true;
        opt.inInputShareable = true;
        opt.inJustDecodeBounds = false;
        InputStream is = context.getResources().openRawResource(resId);
        return BitmapFactory.decodeStream(is, null, opt);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.splash_activity);
        Intent service = new Intent(this, GpsService.class);
        this.startService(service);
        screenOritention();
        initStarList();
        initModemData();
        initMidList();
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                // TODO Auto-generated method stub
                boolean firstLoad = SharedPreferenceManager.getBoolean(mContext, "firstLoad");
                if(firstLoad){
                    SharedPreferenceManager.saveBoolean(mContext, "firstLoad", false);
                    Intent intent = new Intent(SplashActivity.this, WelcomeActivity.class);
                    startActivity(intent);
                    finish();
                }else{
                   String mToken = SharedPreferenceManager.getString(mContext, "mToken");
                    if (mToken == null) {
                        goToLoginActivity();
                    } else {
                        queryStatus(mToken);
                    }
                }

            }
        }, 500);

    }
    private void initMidList() {
        AppData.migIdList.add("8");AppData.migIdList.add("18");AppData.migIdList.add("109");AppData.migIdList.add("13");
        AppData.migIdList.add("110");AppData.migIdList.add("14");AppData.migIdList.add("114");AppData.migIdList.add("15");
        AppData.migIdList.add("27");AppData.migIdList.add("115");AppData.migIdList.add("16");AppData.migIdList.add("116");
        AppData.migIdList.add("17");AppData.migIdList.add("119");AppData.migIdList.add("2");AppData.migIdList.add("4");
        AppData.migIdList.add("28");AppData.migIdList.add("29");AppData.migIdList.add("50");AppData.migIdList.add("51");
        AppData.migIdList.add("52");AppData.migIdList.add("53");AppData.migIdList.add("54");AppData.migIdList.add("120");
        AppData.migIdList.add("6");AppData.migIdList.add("123");AppData.migIdList.add("9");AppData.migIdList.add("112");
        AppData.migIdList.add("5");AppData.migIdList.add("113");AppData.migIdList.add("10");AppData.migIdList.add("117");
        AppData.migIdList.add("7");AppData.migIdList.add("118");AppData.migIdList.add("11");AppData.migIdList.add("121");
        AppData.migIdList.add("12");AppData.migIdList.add("128");AppData.migIdList.add("3");AppData.migIdList.add("104");
        AppData.migIdList.add("25");AppData.migIdList.add("108");AppData.migIdList.add("21");AppData.migIdList.add("103");
        AppData.migIdList.add("19");AppData.migIdList.add("101");AppData.migIdList.add("26");AppData.migIdList.add("111");
        AppData.migIdList.add("23");AppData.migIdList.add("106");AppData.migIdList.add("24");AppData.migIdList.add("107");
        AppData.migIdList.add("20");AppData.migIdList.add("102");AppData.migIdList.add("22");AppData.migIdList.add("105");
    }

    private void goToLoginActivity() {
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                Intent intent = new Intent(mContext, LoginActivity.class);
                startActivity(intent);
                finish();
            }
        }, 2000);

    }
    private void queryStatus(final String mToken) {
        String queryStatusUrl = XTHttpUtil.QUERY_STATUS;
        try {
            JSONObject jsonObject = new JSONObject();
            jsonObject.put("sessionToken", mToken);
            JsonObjectRequest request = new JsonObjectRequest(Request.Method.POST,
                    queryStatusUrl, jsonObject,
                    new Response.Listener<JSONObject>() {
                        @Override
                        public void onResponse(JSONObject response) {
                            try {
                                JSONObject jsonObject = new JSONObject(response.toString());
                                String code = jsonObject.getString("code");
                                if ("0".equals(code)) {
                                    goToHomeActivity(mToken);
                                } else if ("-1".equals(code)) {
                                    goToLoginActivity();
                                } else {
                                    goToLoginActivity();
                                }
                            } catch (JSONException e) {
                                e.printStackTrace();
                            }
                        }
                    }, new Response.ErrorListener() {
                @Override
                public void onErrorResponse(VolleyError error) {
                    goToLoginActivity();
                }
            });
            request.setRetryPolicy(new DefaultRetryPolicy(10 * 1000, 0, 0f));
            AppData.mRequestQueue.add(request);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void goToHomeActivity(final String mToken) {
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                AccountModel accountModel = new AccountModel();
                accountModel.setSessionToken(mToken);
                accountModel.setUser(SharedPreferenceManager.getString(mContext, "user"));
                accountModel.setPasswd(SharedPreferenceManager.getString(mContext, "passwd"));
                AppData.accountModel = accountModel;
                Intent intent = new Intent(mContext, HomeActivity.class);
                startActivity(intent);
                finish();
            }
        }, 1500);


    }
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        // TODO Auto-generated method stub
        super.onConfigurationChanged(newConfig);
    }

    private void screenOritention() {
        if (this.getResources().getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE) {
            Log.i("info", "landscape");
            ImageView splash_img = (ImageView) findViewById(R.id.spalsh_img);
            splash_img.setScaleType(ScaleType.FIT_XY);
            Bitmap bgBitmap = readBitMap(this, R.drawable.luancher_land);
            Drawable drawable = new BitmapDrawable(bgBitmap);
            splash_img.setBackgroundDrawable(drawable);
        } else if (this.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
            Log.i("info", "portrait");
            ImageView splash_img = (ImageView) findViewById(R.id.spalsh_img);
            splash_img.setScaleType(ScaleType.FIT_XY);
            Bitmap bgBitmap = readBitMap(this, R.drawable.qidong);
            Drawable drawable = new BitmapDrawable(bgBitmap);
            splash_img.setBackgroundDrawable(drawable);

        }

    }
    private void initStarList() {
        String initData = SharedPreferenceManager.getString(getApplicationContext(), "initData");
        if (initData == null) {
            StarCodeModel s1 = new StarCodeModel();
            s1.setSatename("协同一号");
            s1.setSatelon("119.5");
            s1.setAmipSwitch("0");
            s1.setMode("0");
            s1.setFreq("960.00");
            s1.setZfreq("12236");
            s1.setCenterFreq("12369");
            s1.setSignRate("60000");
            s1.setBw("0");
            s1.setType("0");
            s1.save();
            StarCodeModel s2 = new StarCodeModel();
            s2.setSatename("亚洲4号");
            s2.setSatelon("122.1");
            s2.save();
            StarCodeModel s3 = new StarCodeModel();
            s3.setSatename("中星10号");
            s3.setSatelon("110.5");
            s3.save();
            StarCodeModel s4 = new StarCodeModel();
            s4.setSatename("中星11号");
            s4.setSatelon("98.0");
            s4.setMode("0");
            s4.setFreq("960.00");
            s4.setZfreq("12236");
            s4.setBw("0");
            s4.setType("0");
            s4.setCenterFreq("12500");
            s4.setSignRate("43200");
            s4.save();
            StarCodeModel s5 = new StarCodeModel();
            s5.setSatename("中星12号");
            s5.setSatelon("87.5");
            s5.setMode("0");
            s5.setFreq("960.00");
            s5.setZfreq("12236");
            s5.setBw("0");
            s5.setType("0");
            s5.setCenterFreq("12514");
            s5.setSignRate("05000");
            s5.save();
            StarCodeModel s6 = new StarCodeModel();
            s6.setSatename("中星9号");
            s6.setSatelon("92.2");
            s6.save();
            StarCodeModel s7 = new StarCodeModel();
            s7.setSatename("中星20号");
            s7.setSatelon("103.2");
            s7.save();
            StarCodeModel s8 = new StarCodeModel();
            s8.setSatename("中星2A");
            s8.setSatelon("98.3");
            s8.save();
            StarCodeModel s9 = new StarCodeModel();
            s9.setSatename("Asiasat-3S");
            s9.setSatelon("146.0");
            s9.save();
            StarCodeModel s10 = new StarCodeModel();
            s10.setSatename("Asiasat-5");
            s10.setSatelon("100.4");
            s10.save();
            StarCodeModel s11 = new StarCodeModel();
            s11.setSatename("Asiasat-7");
            s11.setSatelon("105.5");
            s11.save();
            StarCodeModel s12 = new StarCodeModel();
            s12.setSatename("Apstar-5");
            s12.setSatelon("138.0");
            s12.save();
            StarCodeModel s13 = new StarCodeModel();
            s13.setSatename("Apstar-6");
            s13.setSatelon("134.0");
            s13.save();
            StarCodeModel s14 = new StarCodeModel();
            s14.setSatename("Apstar-7");
            s14.setSatelon("76.5");
            s14.save();
            StarCodeModel s15 = new StarCodeModel();
            s15.setSatename("INSAT-4A");
            s15.setSatelon("83.0");
            s15.save();
            StarCodeModel s16 = new StarCodeModel();
            s16.setSatename("Gsat-10");
            s16.setSatelon("83.0");
            s16.save();
            StarCodeModel s17 = new StarCodeModel();
            s17.setSatename("Palapa-D");
            s17.setSatelon("112.9");
            s17.save();
            StarCodeModel s18 = new StarCodeModel();
            s18.setSatename("Measat-3");
            s18.setSatelon("91.5");
            s18.save();
            StarCodeModel s19 = new StarCodeModel();
            s19.setSatename("Measat-3A");
            s19.setSatelon("91.5");
            s19.save();
            StarCodeModel s20 = new StarCodeModel();
            s20.setSatename("ST-2");
            s20.setSatelon("88.0");
            s20.save();
            StarCodeModel s21 = new StarCodeModel();
            s21.setSatename("Thaicom-5");
            s21.setSatelon("78.5");
            s21.save();
            StarCodeModel s22 = new StarCodeModel();
            s22.setSatename("VinaSat-2");
            s22.setSatelon("131.8");
            s22.save();
            StarCodeModel s23 = new StarCodeModel();
            s23.setSatename("Gsat-8");
            s23.setSatelon("55.1");
            s23.save();
            StarCodeModel s24 = new StarCodeModel();
            s24.setSatename("JCSAT-1B");
            s24.setSatelon("150.0");
            s24.save();
            StarCodeModel s25 = new StarCodeModel();
            s25.setSatename("Superbird-C2");
            s25.setSatelon("143.9");
            s25.save();
            StarCodeModel s26 = new StarCodeModel();
            s26.setSatename("BSAT-3C");
            s26.setSatelon("110.0");
            s26.save();
            StarCodeModel s27 = new StarCodeModel();
            s27.setSatename("BSAT-3B");
            s27.setSatelon("109.8");
            s27.save();
            StarCodeModel s28 = new StarCodeModel();
            s28.setSatename("BSAT-3A");
            s28.setSatelon("109.8");
            s28.save();
            StarCodeModel s29 = new StarCodeModel();
            s29.setSatename("N-SAT110");
            s29.setSatelon("110.0");
            s29.save();
            StarCodeModel s30 = new StarCodeModel();
            s30.setSatename("JCSAT-13");
            s30.setSatelon("124.0");
            s30.save();
            StarCodeModel s31 = new StarCodeModel();
            s31.setSatename("Koreasat-6");
            s31.setSatelon("116.0");
            s31.save();
            StarCodeModel s32 = new StarCodeModel();
            s32.setSatename("INSAT-4CR(Ku)");
            s32.setSatelon("47.8");
            s32.save();
            StarCodeModel s33 = new StarCodeModel();
            s33.setSatename("OPTUS-D1");
            s33.setSatelon("160.0");
            s33.save();
            StarCodeModel s34 = new StarCodeModel();
            s34.setSatename("OPTUS-D3");
            s34.setSatelon("156.0");
            s34.save();
            StarCodeModel s35 = new StarCodeModel();
            s35.setSatename("OPTUS-C1");
            s35.setSatelon("156.0");
            s35.save();
            StarCodeModel s36 = new StarCodeModel();
            s36.setSatename("OPTUS-D2");
            s36.setSatelon("152.0");
            s36.save();
            StarCodeModel s37 = new StarCodeModel();
            s37.setSatename("TURKSAT-3A");
            s37.setSatelon("42.0");
            s37.save();
            StarCodeModel s38 = new StarCodeModel();
            s38.setSatename("Kazsat-2");
            s38.setSatelon("86.5");
            s38.save();
            StarCodeModel s39 = new StarCodeModel();
            s39.setSatename("Express-AM22");
            s39.setSatelon("80.1");
            s39.save();
            StarCodeModel s40 = new StarCodeModel();
            s40.setSatename("Yamal-402");
            s40.setSatelon("54.9");
            s40.save();
            StarCodeModel s41 = new StarCodeModel();
            s41.setSatename("Intelsat-12");
            s41.setSatelon("45.0");
            s41.save();
            StarCodeModel s42 = new StarCodeModel();
            s42.setSatename("Intelsat-15");
            s42.setSatelon("85.2");
            s42.save();
            StarCodeModel s43 = new StarCodeModel();
            s43.setSatename("Astra-1F");
            s43.setSatelon("44.3");
            s43.save();
            StarCodeModel s44 = new StarCodeModel();
            s44.setSatename("NSS-11");
            s44.setSatelon("108.2");
            s44.save();
            LnbDataModel d1 = new LnbDataModel();
            d1.setLnb("9750");
            d1.save();
            LnbDataModel d2 = new LnbDataModel();
            d2.setLnb("10600");
            d2.save();
            LnbDataModel d3 = new LnbDataModel();
            d3.setLnb("10750");
            d3.save();
            LnbDataModel d4 = new LnbDataModel();
            d4.setLnb("11050");
            d4.save();
            LnbDataModel d5= new LnbDataModel();
            d5.setLnb("11300");
            d5.save();
            BucDataModel b1 = new BucDataModel();
            b1.setBucOscillator("12800");
            b1.save();
            BucDataModel b2 = new BucDataModel();
            b2.setBucOscillator("13050");
            b2.save();
            SharedPreferenceManager.saveString(this, "initData", "done");

        }
    }
             private void initModemData () {
                 ModemBean modemBean = new ModemBean();
                 modemBean.setMgid("19");
                 modemBean.setBeam("301");
                 modemBean.setCluster("063A");
                 modemBean.setFreq("12524500");
                 modemBean.setSymbolrate("36000");
                 modemBean.setLnblo("10600000");
                 modemBean.setBuclo("13050000");
                 modemBean.setClustergroup("1");
                 modemBean.save();
                 ModemBean modemBean1 = new ModemBean();
                 modemBean1.setMgid("101");
                 modemBean1.setBeam("301");
                 modemBean1.setCluster("063A");
                 modemBean1.setFreq("12524500");
                 modemBean1.setSymbolrate("36000");
                 modemBean1.setLnblo("10600000");
                 modemBean1.setBuclo("13050000");
                 modemBean1.setClustergroup("1");
                 modemBean1.save();
                 ModemBean modemBean2 = new ModemBean();
                 modemBean2.setMgid("20");
                 modemBean2.setBeam("302");
                 modemBean2.setCluster("067A");
                 modemBean2.setFreq("12714000");
                 modemBean2.setSymbolrate("36000");
                 modemBean2.setLnblo("10600000");
                 modemBean2.setBuclo("13050000");
                 modemBean2.setClustergroup("1");
                 modemBean2.save();
                 ModemBean modemBean3 = new ModemBean();
                 modemBean3.setMgid("102");
                 modemBean3.setBeam("302");
                 modemBean3.setCluster("067A");
                 modemBean3.setFreq("12714000");
                 modemBean3.setSymbolrate("36000");
                 modemBean3.setLnblo("10600000");
                 modemBean3.setBuclo("13050000");
                 modemBean3.setClustergroup("1");
                 modemBean3.save();
                 ModemBean modemBean4 = new ModemBean();
                 modemBean4.setMgid("21");
                 modemBean4.setBeam("303");
                 modemBean4.setCluster("062A");
                 modemBean4.setFreq("12236000");
                 modemBean4.setSymbolrate("36000");
                 modemBean4.setLnblo("10600000");
                 modemBean4.setBuclo("13050000");
                 modemBean4.setClustergroup("1");
                 modemBean4.save();
                 ModemBean modemBean5 = new ModemBean();
                 modemBean5.setMgid("103");
                 modemBean5.setBeam("303");
                 modemBean5.setCluster("062A");
                 modemBean5.setFreq("12236000");
                 modemBean5.setSymbolrate("36000");
                 modemBean5.setLnblo("10600000");
                 modemBean5.setBuclo("13050000");
                 modemBean5.setClustergroup("1");
                 modemBean5.save();
                 ModemBean modemBean6 = new ModemBean();
                 modemBean6.setMgid("3");
                 modemBean6.setBeam("304");
                 modemBean6.setCluster("060A");
                 modemBean6.setFreq("12524500");
                 modemBean6.setSymbolrate("60000");
                 modemBean6.setLnblo("10600000");
                 modemBean6.setBuclo("13050000");
                 modemBean6.setClustergroup("1");
                 modemBean6.save();
                 ModemBean modemBean7 = new ModemBean();
                 modemBean7.setMgid("104");
                 modemBean7.setBeam("304");
                 modemBean7.setCluster("060A");
                 modemBean7.setFreq("12524500");
                 modemBean7.setSymbolrate("60000");
                 modemBean7.setLnblo("10600000");
                 modemBean7.setBuclo("13050000");
                 modemBean7.setClustergroup("1");
                 modemBean7.save();
                 ModemBean modemBean8 = new ModemBean();
                 modemBean8.setMgid("22");
                 modemBean8.setBeam("305");
                 modemBean8.setCluster("068A");
                 modemBean8.setFreq("12714000");
                 modemBean8.setSymbolrate("36000");
                 modemBean8.setLnblo("10600000");
                 modemBean8.setBuclo("13050000");
                 modemBean8.setClustergroup("1");
                 modemBean8.save();
                 ModemBean modemBean9 = new ModemBean();
                 modemBean9.setMgid("105");
                 modemBean9.setBeam("305");
                 modemBean9.setCluster("068A");
                 modemBean9.setFreq("12714000");
                 modemBean9.setSymbolrate("36000");
                 modemBean9.setLnblo("10600000");
                 modemBean9.setBuclo("13050000");
                 modemBean9.setClustergroup("1");
                 modemBean9.save();
                 ModemBean modemBean10 = new ModemBean();
                 modemBean10.setMgid("23");
                 modemBean10.setBeam("306");
                 modemBean10.setCluster("065A");
                 modemBean10.setFreq("12524500");
                 modemBean10.setSymbolrate("36000");
                 modemBean10.setLnblo("10600000");
                 modemBean10.setBuclo("13050000");
                 modemBean10.setClustergroup("1");
                 modemBean10.save();
                 ModemBean modemBean11 = new ModemBean();
                 modemBean11.setMgid("106");
                 modemBean11.setBeam("306");
                 modemBean11.setCluster("065A");
                 modemBean11.setFreq("12524500");
                 modemBean11.setSymbolrate("36000");
                 modemBean11.setLnblo("10600000");
                 modemBean11.setBuclo("13050000");
                 modemBean11.setClustergroup("1");
                 modemBean11.save();
                 ModemBean modemBean12 = new ModemBean();
                 modemBean12.setMgid("24");
                 modemBean12.setBeam("307");
                 modemBean12.setCluster("066A");
                 modemBean12.setFreq("12714000");
                 modemBean12.setSymbolrate("36000");
                 modemBean12.setLnblo("10600000");
                 modemBean12.setBuclo("13050000");
                 modemBean12.setClustergroup("1");
                 modemBean12.save();
                 ModemBean modemBean13 = new ModemBean();
                 modemBean13.setMgid("107");
                 modemBean13.setBeam("307");
                 modemBean13.setCluster("066A");
                 modemBean13.setFreq("12714000");
                 modemBean13.setSymbolrate("36000");
                 modemBean13.setLnblo("10600000");
                 modemBean13.setBuclo("13050000");
                 modemBean13.setClustergroup("1");
                 modemBean13.save();
                 ModemBean modemBean14 = new ModemBean();
                 modemBean14.setMgid("25");
                 modemBean14.setBeam("308");
                 modemBean14.setCluster("061A");
                 modemBean14.setFreq("12335000");
                 modemBean14.setSymbolrate("36000");
                 modemBean14.setLnblo("10600000");
                 modemBean14.setBuclo("13050000");
                 modemBean14.setClustergroup("1");
                 modemBean14.save();
                 ModemBean modemBean15 = new ModemBean();
                 modemBean15.setMgid("108");
                 modemBean15.setBeam("308");
                 modemBean15.setCluster("061A");
                 modemBean15.setFreq("12335000");
                 modemBean15.setSymbolrate("36000");
                 modemBean15.setLnblo("10600000");
                 modemBean15.setBuclo("13050000");
                 modemBean15.setClustergroup("1");
                 modemBean15.save();
                 ModemBean modemBean16 = new ModemBean();
                 modemBean16.setMgid("8");
                 modemBean16.setBeam("309");
                 modemBean16.setCluster("052A");
                 modemBean16.setFreq("12524500");
                 modemBean16.setSymbolrate("60000");
                 modemBean16.setLnblo("10600000");
                 modemBean16.setBuclo("13050000");
                 modemBean16.setClustergroup("1");
                 modemBean16.save();
                 ModemBean modemBean17 = new ModemBean();
                 modemBean17.setMgid("18");
                 modemBean17.setBeam("309");
                 modemBean17.setCluster("052A");
                 modemBean17.setFreq("12524500");
                 modemBean17.setSymbolrate("60000");
                 modemBean17.setLnblo("10600000");
                 modemBean17.setBuclo("13050000");
                 modemBean17.setClustergroup("1");
                 modemBean17.save();
                 ModemBean modemBean18 = new ModemBean();
                 modemBean18.setMgid("109");
                 modemBean18.setBeam("309");
                 modemBean18.setCluster("052A");
                 modemBean18.setFreq("12524500");
                 modemBean18.setSymbolrate("60000");
                 modemBean18.setLnblo("10600000");
                 modemBean18.setBuclo("13050000");
                 modemBean18.setClustergroup("1");
                 modemBean18.save();
                 ModemBean modemBean19 = new ModemBean();
                 modemBean19.setMgid("13");
                 modemBean19.setBeam("310");
                 modemBean19.setCluster("058A");
                 modemBean19.setFreq("12714000");
                 modemBean19.setSymbolrate("60000");
                 modemBean19.setLnblo("10600000");
                 modemBean19.setBuclo("13050000");
                 modemBean19.setClustergroup("1");
                 modemBean19.save();
                 ModemBean modemBean20 = new ModemBean();
                 modemBean20.setMgid("110");
                 modemBean20.setBeam("310");
                 modemBean20.setCluster("058A");
                 modemBean20.setFreq("12714000");
                 modemBean20.setSymbolrate("60000");
                 modemBean20.setLnblo("10600000");
                 modemBean20.setBuclo("13050000");
                 modemBean20.setClustergroup("1");
                 modemBean20.save();
                 ModemBean modemBean21 = new ModemBean();
                 modemBean21.setMgid("26");
                 modemBean21.setBeam("311");
                 modemBean21.setCluster("064A");
                 modemBean21.setFreq("12236000");
                 modemBean21.setSymbolrate("36000");
                 modemBean21.setLnblo("10600000");
                 modemBean21.setBuclo("13050000");
                 modemBean21.setClustergroup("1");
                 modemBean21.save();
                 ModemBean modemBean22 = new ModemBean();
                 modemBean22.setMgid("111");
                 modemBean22.setBeam("311");
                 modemBean22.setCluster("064A");
                 modemBean22.setFreq("12236000");
                 modemBean22.setSymbolrate("36000");
                 modemBean22.setLnblo("10600000");
                 modemBean22.setBuclo("13050000");
                 modemBean22.setClustergroup("1");
                 modemBean22.save();
                 ModemBean modemBean23 = new ModemBean();
                 modemBean23.setMgid("9");
                 modemBean23.setBeam("312");
                 modemBean23.setCluster("071A");
                 modemBean23.setFreq("12524500");
                 modemBean23.setSymbolrate("60000");
                 modemBean23.setLnblo("10600000");
                 modemBean23.setBuclo("13050000");
                 modemBean23.setClustergroup("1");
                 modemBean23.save();
                 ModemBean modemBean24 = new ModemBean();
                 modemBean24.setMgid("112");
                 modemBean24.setBeam("312");
                 modemBean24.setCluster("071A");
                 modemBean24.setFreq("12524500");
                 modemBean24.setSymbolrate("60000");
                 modemBean24.setLnblo("10600000");
                 modemBean24.setBuclo("13050000");
                 modemBean24.setClustergroup("1");
                 modemBean24.save();
                 ModemBean modemBean25 = new ModemBean();
                 modemBean25.setMgid("5");
                 modemBean25.setBeam("313");
                 modemBean25.setCluster("070A");
                 modemBean25.setFreq("12714000");
                 modemBean25.setSymbolrate("60000");
                 modemBean25.setLnblo("10600000");
                 modemBean25.setBuclo("13050000");
                 modemBean25.setClustergroup("1");
                 modemBean25.save();
                 ModemBean modemBean26= new ModemBean();
                 modemBean26.setMgid("113");
                 modemBean26.setBeam("313");
                 modemBean26.setCluster("070A");
                 modemBean26.setFreq("12714000");
                 modemBean26.setSymbolrate("60000");
                 modemBean26.setLnblo("10600000");
                 modemBean26.setBuclo("13050000");
                 modemBean26.setClustergroup("1");
                 modemBean26.save();
                 ModemBean modemBean27 = new ModemBean();
                 modemBean27.setMgid("14");
                 modemBean27.setBeam("314");
                 modemBean27.setCluster("057A");
                 modemBean27.setFreq("12714000");
                 modemBean27.setSymbolrate("60000");
                 modemBean27.setLnblo("10600000");
                 modemBean27.setBuclo("13050000");
                 modemBean27.setClustergroup("1");
                 modemBean27.save();
                 ModemBean modemBean28 = new ModemBean();
                 modemBean28.setMgid("114");
                 modemBean28.setBeam("314");
                 modemBean28.setCluster("057A");
                 modemBean28.setFreq("12714000");
                 modemBean28.setSymbolrate("60000");
                 modemBean28.setLnblo("10600000");
                 modemBean28.setBuclo("13050000");
                 modemBean28.setClustergroup("1");
                 modemBean28.save();
                 ModemBean modemBean29 = new ModemBean();
                 modemBean29.setMgid("15");
                 modemBean29.setBeam("315");
                 modemBean29.setCluster("056A");
                 modemBean29.setFreq("12335000");
                 modemBean29.setSymbolrate("60000");
                 modemBean29.setLnblo("10600000");
                 modemBean29.setBuclo("13050000");
                 modemBean29.setClustergroup("1");
                 modemBean29.save();
                 ModemBean modemBean30 = new ModemBean();
                 modemBean30.setMgid("27");
                 modemBean30.setBeam("315");
                 modemBean30.setCluster("056A");
                 modemBean30.setFreq("12335000");
                 modemBean30.setSymbolrate("60000");
                 modemBean30.setLnblo("10600000");
                 modemBean30.setBuclo("13050000");
                 modemBean30.setClustergroup("1");
                 modemBean30.save();
                 ModemBean modemBean31 = new ModemBean();
                 modemBean31.setMgid("115");
                 modemBean31.setBeam("315");
                 modemBean31.setCluster("056A");
                 modemBean31.setFreq("12335000");
                 modemBean31.setSymbolrate("60000");
                 modemBean31.setLnblo("10600000");
                 modemBean31.setBuclo("13050000");
                 modemBean31.setClustergroup("1");
                 modemBean31.save();
                 ModemBean modemBean32 = new ModemBean();
                 modemBean32.setMgid("16");
                 modemBean32.setBeam("316");
                 modemBean32.setCluster("054A");
                 modemBean32.setFreq("12524500");
                 modemBean32.setSymbolrate("60000");
                 modemBean32.setLnblo("10600000");
                 modemBean32.setBuclo("13050000");
                 modemBean32.setClustergroup("1");
                 modemBean32.save();
                 ModemBean modemBean33 = new ModemBean();
                 modemBean33.setMgid("116");
                 modemBean33.setBeam("316");
                 modemBean33.setCluster("054A");
                 modemBean33.setFreq("12524500");
                 modemBean33.setSymbolrate("60000");
                 modemBean33.setLnblo("10600000");
                 modemBean33.setBuclo("13050000");
                 modemBean33.setClustergroup("1");
                 modemBean33.save();
                 ModemBean modemBean34 = new ModemBean();
                 modemBean34.setMgid("10");
                 modemBean34.setBeam("317");
                 modemBean34.setCluster("074A");
                 modemBean34.setFreq("12714000");
                 modemBean34.setSymbolrate("60000");
                 modemBean34.setLnblo("10600000");
                 modemBean34.setBuclo("13050000");
                 modemBean34.setClustergroup("1");
                 modemBean34.save();
                 ModemBean modemBean35 = new ModemBean();
                 modemBean35.setMgid("117");
                 modemBean35.setBeam("317");
                 modemBean35.setCluster("074A");
                 modemBean35.setFreq("12714000");
                 modemBean35.setSymbolrate("60000");
                 modemBean35.setLnblo("10600000");
                 modemBean35.setBuclo("13050000");
                 modemBean35.setClustergroup("1");
                 modemBean35.save();
                 ModemBean modemBean36 = new ModemBean();
                 modemBean36.setMgid("7");
                 modemBean36.setBeam("318");
                 modemBean36.setCluster("072A");
                 modemBean36.setFreq("12335000");
                 modemBean36.setSymbolrate("60000");
                 modemBean36.setLnblo("10600000");
                 modemBean36.setBuclo("13050000");
                 modemBean36.setClustergroup("1");
                 modemBean36.save();
                 ModemBean modemBean37 = new ModemBean();
                 modemBean37.setMgid("118");
                 modemBean37.setBeam("318");
                 modemBean37.setCluster("072A");
                 modemBean37.setFreq("12335000");
                 modemBean37.setSymbolrate("60000");
                 modemBean37.setLnblo("10600000");
                 modemBean37.setBuclo("13050000");
                 modemBean37.setClustergroup("1");
                 modemBean37.save();
                 ModemBean modemBean38 = new ModemBean();
                 modemBean38.setMgid("17");
                 modemBean38.setBeam("319");
                 modemBean38.setCluster("055A");
                 modemBean38.setFreq("12714000");
                 modemBean38.setSymbolrate("60000");
                 modemBean38.setLnblo("10600000");
                 modemBean38.setBuclo("13050000");
                 modemBean38.setClustergroup("1");
                 modemBean38.save();
                 ModemBean modemBean39 = new ModemBean();
                 modemBean39.setMgid("119");
                 modemBean39.setBeam("319");
                 modemBean39.setCluster("055A");
                 modemBean39.setFreq("12714000");
                 modemBean39.setSymbolrate("60000");
                 modemBean39.setLnblo("10600000");
                 modemBean39.setBuclo("13050000");
                 modemBean39.setClustergroup("1");
                 modemBean39.save();
                 ModemBean modemBean40 = new ModemBean();
                 modemBean40.setMgid("2");
                 modemBean40.setBeam("320");
                 modemBean40.setCluster("051A");
                 modemBean40.setFreq("12236000");
                 modemBean40.setSymbolrate("60000");
                 modemBean40.setLnblo("10600000");
                 modemBean40.setBuclo("13050000");
                 modemBean40.setClustergroup("1");
                 modemBean40.save();
                 ModemBean modemBean41 = new ModemBean();
                 modemBean41.setMgid("4");
                 modemBean41.setBeam("320");
                 modemBean41.setCluster("051A");
                 modemBean41.setFreq("12236000");
                 modemBean41.setSymbolrate("60000");
                 modemBean41.setLnblo("10600000");
                 modemBean41.setBuclo("13050000");
                 modemBean41.setClustergroup("1");
                 modemBean41.save();
                 ModemBean modemBean42 = new ModemBean();
                 modemBean42.setMgid("28");
                 modemBean42.setBeam("320");
                 modemBean42.setCluster("051A");
                 modemBean42.setFreq("12236000");
                 modemBean42.setSymbolrate("60000");
                 modemBean42.setLnblo("10600000");
                 modemBean42.setBuclo("13050000");
                 modemBean42.setClustergroup("1");
                 modemBean42.save();
                 ModemBean modemBean43 = new ModemBean();
                 modemBean43.setMgid("29");
                 modemBean43.setBeam("320");
                 modemBean43.setCluster("051A");
                 modemBean43.setFreq("12236000");
                 modemBean43.setSymbolrate("60000");
                 modemBean43.setLnblo("10600000");
                 modemBean43.setBuclo("13050000");
                 modemBean43.setClustergroup("1");
                 modemBean43.save();
                 ModemBean modemBean44 = new ModemBean();
                 modemBean44.setMgid("50");
                 modemBean44.setBeam("320");
                 modemBean44.setCluster("051A");
                 modemBean44.setFreq("12236000");
                 modemBean44.setSymbolrate("60000");
                 modemBean44.setLnblo("10600000");
                 modemBean44.setBuclo("13050000");
                 modemBean44.setClustergroup("1");
                 modemBean44.save();
                 ModemBean modemBean45 = new ModemBean();
                 modemBean45.setMgid("51");
                 modemBean45.setBeam("320");
                 modemBean45.setCluster("051A");
                 modemBean45.setFreq("12236000");
                 modemBean45.setSymbolrate("60000");
                 modemBean45.setLnblo("10600000");
                 modemBean45.setBuclo("13050000");
                 modemBean45.setClustergroup("1");
                 modemBean45.save();
                 ModemBean modemBean46 = new ModemBean();
                 modemBean46.setMgid("52");
                 modemBean46.setBeam("320");
                 modemBean46.setCluster("051A");
                 modemBean46.setFreq("12236000");
                 modemBean46.setSymbolrate("60000");
                 modemBean46.setLnblo("10600000");
                 modemBean46.setBuclo("13050000");
                 modemBean46.setClustergroup("1");
                 modemBean46.save();
                 ModemBean modemBean47 = new ModemBean();
                 modemBean47.setMgid("53");
                 modemBean47.setBeam("320");
                 modemBean47.setCluster("051A");
                 modemBean47.setFreq("12236000");
                 modemBean47.setSymbolrate("60000");
                 modemBean47.setLnblo("10600000");
                 modemBean47.setBuclo("13050000");
                 modemBean47.setClustergroup("1");
                 modemBean47.save();
                 ModemBean modemBean48 = new ModemBean();
                 modemBean48.setMgid("54");
                 modemBean48.setBeam("320");
                 modemBean48.setCluster("051A");
                 modemBean48.setFreq("12236000");
                 modemBean48.setSymbolrate("60000");
                 modemBean48.setLnblo("10600000");
                 modemBean48.setBuclo("13050000");
                 modemBean48.setClustergroup("1");
                 modemBean48.save();
                 ModemBean modemBean49 = new ModemBean();
                 modemBean49.setMgid("120");
                 modemBean49.setBeam("320");
                 modemBean49.setCluster("051A");
                 modemBean49.setFreq("12236000");
                 modemBean49.setSymbolrate("60000");
                 modemBean49.setLnblo("10600000");
                 modemBean49.setBuclo("13050000");
                 modemBean49.setClustergroup("1");
                 modemBean49.save();
                 ModemBean modemBean50 = new ModemBean();
                 modemBean50.setMgid("11");
                 modemBean50.setBeam("321");
                 modemBean50.setCluster("073A");
                 modemBean50.setFreq("12524500");
                 modemBean50.setSymbolrate("60000");
                 modemBean50.setLnblo("10600000");
                 modemBean50.setBuclo("13050000");
                 modemBean50.setClustergroup("1");
                 modemBean50.save();
                 ModemBean modemBean51 = new ModemBean();
                 modemBean51.setMgid("121");
                 modemBean51.setBeam("321");
                 modemBean51.setCluster("073A");
                 modemBean51.setFreq("12524500");
                 modemBean51.setSymbolrate("60000");
                 modemBean51.setLnblo("10600000");
                 modemBean51.setBuclo("13050000");
                 modemBean51.setClustergroup("1");
                 modemBean51.save();
                 ModemBean modemBean52 = new ModemBean();
                 modemBean52.setMgid("6");
                 modemBean52.setBeam("323");
                 modemBean52.setCluster("053A");
                 modemBean52.setFreq("12524500");
                 modemBean52.setSymbolrate("60000");
                 modemBean52.setLnblo("10600000");
                 modemBean52.setBuclo("13050000");
                 modemBean52.setClustergroup("1");
                 modemBean52.save();
                 ModemBean modemBean53 = new ModemBean();
                 modemBean53.setMgid("123");
                 modemBean53.setBeam("323");
                 modemBean53.setCluster("053A");
                 modemBean53.setFreq("12524500");
                 modemBean53.setSymbolrate("60000");
                 modemBean53.setLnblo("10600000");
                 modemBean53.setBuclo("13050000");
                 modemBean53.setClustergroup("1");
                 modemBean53.save();
                 ModemBean modemBean54 = new ModemBean();
                 modemBean54.setMgid("12");
                 modemBean54.setBeam("328");
                 modemBean54.setCluster("075A");
                 modemBean54.setFreq("11046000");
                 modemBean54.setSymbolrate("60000");
                 modemBean54.setLnblo("10600000");
                 modemBean54.setBuclo("13050000");
                 modemBean54.setClustergroup("1");
                 modemBean54.save();
                 ModemBean modemBean55 = new ModemBean();
                 modemBean55.setMgid("128");
                 modemBean55.setBeam("328");
                 modemBean55.setCluster("075A");
                 modemBean55.setFreq("11046000");
                 modemBean55.setSymbolrate("60000");
                 modemBean55.setLnblo("10600000");
                 modemBean55.setBuclo("13050000");
                 modemBean55.setClustergroup("1");
                 modemBean55.save();
             }
}
