//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : backParentListener.java
//  @ Date : 2013-8-14
//  @ Author : Eric Huang <htb@my51c.com>
//
//
package com.my51c.see51.listener;

/**
 * ���ظ�������ӿ� <br>
 * **** &nbsp;&nbsp��Ҫ�������ظ������¼��Ķ���ʵ�ָýӿڣ�<br>
 * ��������ذ���ʱ������Ҫ������һ��ʱ�����ô˽ӿ�
 */
public interface BackParentListener {
    void backParent();
}


