//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : See51
//  @ File Name : DeviceEventListener.java
//  @ Date : 2012-5-30
//  @ Author : Eric Guo <gjl@my51c.com>
//
//


package com.my51c.see51.listener;

/**
 * �豸�б�����ӿ� <br>
 * **** &nbsp;&nbsp��Ҫ�����б�ı��¼��Ķ���ʵ�ָýӿڣ���������ͨ��DeviceList��addListListener����ע�ᵽ�豸�б�<br>
 * ���豸�б����ı�ʱ�����ô˽ӿ�
 */

public interface DeviceListListener {
    void onListUpdate();
}
